---
abstract: 'extract the unique elements of a list'
author:
  - 'James FitzGibbon, <james+perl@nadt.net>'
build_requires:
  ExtUtils::MakeMaker: '6.46'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.46'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.56, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: List-Uniq
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/renderorange/List-Uniq/issues
  repository: https://github.com/renderorange/List-Uniq.git
version: '0.23'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
